#
# Makefile for making STATIC version of the - salish_500m - executable.
#

SHELL	= /bin/sh

name	= salish_500m
setup	= $(name)

include ../Rules.make

STATIC += -DSTATIC -DSPHERICAL

.PHONY: input
input:
