#
# Makefile for making STATIC version of the - salish_2km - executable.
#

SHELL	= /bin/sh

name	= salish_2km
setup	= $(name)

include ../Rules.make

STATIC += -DSTATIC -DSPHERICAL

.PHONY: input
input:
